### ISSUE TITLE
[BUG] Faulty Hitbox For Cards in Hand

### ISSUE THREAD

**Issue by KOOKIIEStudios** [BAA-Studios/MOOgiwara#55] opened 2023-02-12 01:59 UTC
**Describe the bug**
With the way the hand is currently being rendered, cards slightly overlap, with the left edge of cards on the right being on top of the right edge of cards on the left. As such, it would be expected for the cards on the right to behave as if it were on top of the one to its left. However, the actual hitbox detection seems to imply otherwise (see screenshot).

**Screenshots**
![image](https://user-images.githubusercontent.com/25145447/218288863-3e23b3b1-a264-4889-8ef1-b1b626955a05.png)  
From the above, we can see that the cursor is still placed on the card on the right, but the hitbox for the card on the left has detected a mouseover event, and greyed it out.

**Comment by Bratah123** [comment] 2023-02-12 03:48
## Note
I unintentionally fixed this issue by switching around phaser versions

Steps to Reproduce:
1. npm install on Ichika 3.55.2 build of Phaser (Game will crash on 'destroy')
2. change to the beta build of Phaser and npm install
3. cards will have hover priority correctly

I managed to reproduce this fix TWICE once on my main PC and once on my Laptop whilst setting up MOOgiwara development environment.

@ta-lyx managed to reproduce the by running `npm install` after my commit in: https://github.com/BAA-Studios/MOOgiwara/commit/7e8cd0267655b8d96577ec7438b64f7ebe8e4cab

**Comment by Bratah123** [comment] 2023-06-09 04:01
Closing because this bug was fixed in a commit that I cannot find but remember, that had to do with phaser versioning!

**Closed by Bratah123** 2023-06-09 04:01 UTC
Labels: bug
